import type { Category, Course, CoursesByCategory, Instructor } from '@/types'

export const INSTRUCTORS: readonly Instructor[] = [
  { name: 'Елена Златоцвет', avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=elena&backgroundColor=b6e3f4' },
  { name: 'Мирослав Огненный', avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=miroslav&backgroundColor=c0aede' },
  { name: 'Ирина Лунная', avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=irina&backgroundColor=d1d4f9' },
  { name: 'Велимир Руновед', avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=velimir&backgroundColor=ffd5dc' },
  { name: 'Светлана Звёздная', avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=svetlana&backgroundColor=ffdfbf' },
  { name: 'Арктур Северный', avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=arktur&backgroundColor=b6e3f4' },
] as const

export const CATEGORIES: readonly Category[] = [
  {
    id: 'sephirotic',
    label: 'Сефиротическая магия',
    teaser: 'Изучение древа жизни и десяти сефирот как инструментов трансформации сознания и работы с энергией.',
    fullDescription: 'Сефиротическая магия — это система работы с Древом Жизни, основанная на каббалистической традиции. Каждая сефира представляет собой определённый аспект Вселенной и человеческой души. Курсы этого направления помогут вам освоить медитацию на сефирот, научиться работать с путями между ними и интегрировать эту мощную систему в свою ежедневную практику. Вы научитесь распознавать энергетические паттерны и направлять поток силы через различные уровни бытия.',
  },
  {
    id: 'nordic',
    label: 'Магия Севера',
    teaser: 'Скандинавские традиции, работа с рунами, сейд и шаманские практики Севера.',
    fullDescription: 'Магия Севера охватывает широкий спектр практик, уходящих корнями в скандинавскую и германскую традиции. Здесь вы найдёте курсы по работе с рунами, практике сейда, галдра и шаманским путешествиям. Северная магия учит взаимодействию с природными силами, духами мест и предками. Каждый курс сочетает теоретическую базу с практическими упражнениями, позволяя интегрировать древнюю мудрость в современную жизнь.',
  },
  {
    id: 'feminine',
    label: 'Женская магия',
    teaser: 'Пробуждение женской силы, лунные ритуалы и практики работы с женской энергией.',
    fullDescription: 'Женская магия — это путь к пробуждению сакральной женской силы через работу с лунными циклами, элементами природы и архетипами Богини. Курсы этого направления помогут вам наладить связь с собственным телом, развить интуицию и научиться использовать циклическую природу женской энергии. Практики включают лунные ритуалы, работу с кругом сестёр, медитации на пробуждение Кундалини и техники исцеления женской линии рода.',
  },
  {
    id: 'runes',
    label: 'Руническая магия',
    teaser: 'Глубокое изучение рунического алфавита, создание ставов и гадание на рунах.',
    fullDescription: 'Руническая магия — это искусство работы с древними символами силы, каждый из которых является ключом к определённому аспекту реальности. В наших курсах вы изучите Старший и Младший Футарк, научитесь создавать рунические ставы и формулы, освоите технику рунического гадания и защитные практики. Особое внимание уделяется энергетической настройке на каждую руну и пониманию её глубинного смысла через медитацию и практическую работу.',
  },
  {
    id: 'numerology',
    label: 'Нумерология',
    teaser: 'Мистика чисел, вычисление жизненного пути и работа с числовыми вибрациями.',
    fullDescription: 'Нумерология раскрывает тайный язык чисел, пронизывающий всю ткань реальности. Наши курсы охватывают пифагорейскую, каббалистическую и ведическую нумерологию. Вы научитесь составлять нумерологические карты, определять числа судьбы, жизненного пути и души, а также использовать силу чисел для гармонизации пространства, выбора дат и понимания жизненных циклов. Каждый курс включает практические задания и реальные разборы.',
  },
  {
    id: 'energy',
    label: 'Энергетические практики',
    teaser: 'Работа с энергетическим телом, чакрами, аурой и потоками жизненной силы.',
    fullDescription: 'Энергетические практики — это фундамент любой магической работы. В этом разделе вы найдёте курсы по работе с чакрами, очищению и укреплению ауры, техникам заземления и центрирования, а также продвинутые практики работы с Кундалини и тонкими энергиями. Программы разработаны опытными преподавателями и включают пошаговые инструкции, медитации и упражнения для развития энергетической чувствительности.',
  },
  {
    id: 'voodoo',
    label: 'Магия Вуду',
    teaser: 'Традиции Вуду, работа с Лоа, ритуалы на перекрёстке и создание гри-гри.',
    fullDescription: 'Магия Вуду — это мощная духовная система, зародившаяся в Западной Африке и развившаяся в Гаити и Новом Орлеане. Наши курсы охватывают работу с Лоа (духами), создание алтарей, рисование вевé, использование гри-гри и моджо-мешочков, а также ритуальные практики на перекрёстках. Особое внимание уделяется уважительному подходу к традиции, связи с предками и пониманию космологии Вуду. Каждый курс сочетает глубокое теоретическое знание с безопасными практическими техниками.',
  },
  {
    id: 'alchemy',
    label: 'Алхимия',
    teaser: 'Искусство трансмутации, работа с первоматерией и философский камень.',
    fullDescription: 'Алхимия — это древнее искусство трансформации, объединяющее духовную и материальную работу. В наших курсах вы изучите три стадии Великого Делания — нигредо, альбедо и рубедо, — научитесь работать с алхимическими символами и элементами, постигнете тайны Изумрудной Скрижали и принцип «как вверху, так и внизу». Программы включают практическую спагирию (растительную алхимию), медитативные практики внутренней трансмутации и изучение герметической философии как основы всех магических традиций.',
  },
] as const

const createCourse = (
  id: string,
  title: string,
  instructorIndex: number,
  image: string,
  price: string,
  lessons: number
): Course => {
  const instructor = INSTRUCTORS[instructorIndex]
  if (!instructor) {
    throw new Error(`Invalid instructor index: ${instructorIndex}`)
  }
  return {
    id,
    title,
    instructor: instructor.name,
    avatar: instructor.avatar,
    image,
    price,
    lessons,
  }
}

export const COURSES_BY_CATEGORY: CoursesByCategory = {
  sephirotic: [
    createCourse('s1', 'Основы Сефиротической Магии: Путь по Древу Жизни', 0, '/images/course-sephirotic-1.jpg', '12 900 ₽', 16),
    createCourse('s2', 'Продвинутые практики Каббалы: Работа с Путями', 1, '/images/course-sephirotic-2.jpg', '18 500 ₽', 24),
    createCourse('s3', 'Медитации на Сефирот: Трансформация через Свет', 2, '/images/course-sephirotic-3.jpg', '9 900 ₽', 12),
    createCourse('s4', 'Малкут и Заземление: Фундамент Магической Работы', 0, '/images/course-sephirotic-1.jpg', '7 500 ₽', 8),
    createCourse('s5', 'Тиферет: Сердце Древа Жизни и Гармония Сил', 4, '/images/course-sephirotic-2.jpg', '14 200 ₽', 18),
    createCourse('s6', 'Кетер и Высшее Сознание: Путь к Единству', 1, '/images/course-sephirotic-3.jpg', '21 000 ₽', 30),
    createCourse('s7', 'Столп Милосердия: Хесед, Хокма и Нецах', 2, '/images/course-sephirotic-1.jpg', '16 800 ₽', 22),
    createCourse('s8', 'Столп Строгости: Гебура, Бина и Ход', 0, '/images/course-sephirotic-2.jpg', '16 800 ₽', 22),
    createCourse('s9', 'Даат: Тайная Сефира и Бездна Познания', 1, '/images/course-sephirotic-3.jpg', '19 900 ₽', 26),
    createCourse('s10', 'Ритуалы Каббалистической Магии: Практикум', 5, '/images/course-sephirotic-1.jpg', '15 500 ₽', 20),
    createCourse('s11', 'Сефиротическая Астрология: Планеты и Древо', 4, '/images/course-sephirotic-2.jpg', '13 200 ₽', 16),
    createCourse('s12', 'Еврейские Буквы Силы: Алфавит и Магия', 0, '/images/course-sephirotic-3.jpg', '11 900 ₽', 14),
    createCourse('s13', 'Йесод и Астральный План: Практика Сновидений', 2, '/images/course-sephirotic-1.jpg', '10 500 ₽', 12),
    createCourse('s14', 'Защитные Практики Каббалы: Щит Древа Жизни', 3, '/images/course-sephirotic-2.jpg', '8 900 ₽', 10),
    createCourse('s15', 'Каббала и Таро: Путешествие Глупца по Древу', 4, '/images/course-sephirotic-3.jpg', '17 500 ₽', 22),
  ],
  nordic: [
    createCourse('n1', 'Магия Севера: Сейд и Шаманские Путешествия', 5, '/images/course-nordic-1.jpg', '14 500 ₽', 18),
    createCourse('n2', 'Северные Ритуалы: Блот и Жертвоприношения Богам', 1, '/images/course-nordic-2.jpg', '11 900 ₽', 14),
    createCourse('n3', 'Скандинавская Космология: Девять Миров', 5, '/images/course-nordic-3.jpg', '16 000 ₽', 20),
    createCourse('n4', 'Гальдр: Магия Голоса и Звуковые Заклинания', 1, '/images/course-nordic-1.jpg', '13 200 ₽', 16),
    createCourse('n5', 'Вёльва: Практика Северного Пророчества', 2, '/images/course-nordic-2.jpg', '15 800 ₽', 20),
    createCourse('n6', 'Путь Воина: Берсерк и Боевая Магия', 5, '/images/course-nordic-3.jpg', '17 200 ₽', 22),
    createCourse('n7', 'Один и Руны Мудрости: Жертва на Иггдрасиле', 3, '/images/course-nordic-1.jpg', '19 500 ₽', 26),
    createCourse('n8', 'Фрейя и Сила Ванов: Магия Плодородия', 2, '/images/course-nordic-2.jpg', '12 400 ₽', 14),
    createCourse('n9', 'Тёмная Хель: Работа с Миром Мёртвых', 1, '/images/course-nordic-3.jpg', '18 000 ₽', 24),
    createCourse('n10', 'Альфхейм: Связь с Духами Природы', 4, '/images/course-nordic-1.jpg', '10 500 ₽', 12),
    createCourse('n11', 'Мидгард и Заземление: Магия Повседневности', 0, '/images/course-nordic-2.jpg', '8 900 ₽', 10),
    createCourse('n12', 'Нидхёгг и Теневая Работа: Тёмная Сторона', 5, '/images/course-nordic-3.jpg', '16 500 ₽', 20),
    createCourse('n13', 'Тор и Защитная Магия: Молот Мьёльнир', 3, '/images/course-nordic-1.jpg', '11 200 ₽', 14),
    createCourse('n14', 'Норны и Судьба: Плетение Урд, Верданди, Скульд', 2, '/images/course-nordic-2.jpg', '14 800 ₽', 18),
    createCourse('n15', 'Рагнарёк: Трансформация через Разрушение', 1, '/images/course-nordic-3.jpg', '20 000 ₽', 28),
  ],
  feminine: [
    createCourse('f1', 'Пробуждение Женской Силы: Лунные Мистерии', 2, '/images/course-feminine-1.jpg', '13 900 ₽', 16),
    createCourse('f2', 'Круг Сестёр: Групповые Ритуалы и Практики', 4, '/images/course-feminine-2.jpg', '8 900 ₽', 10),
    createCourse('f3', 'Сакральная Женственность: Архетипы Богини', 2, '/images/course-feminine-3.jpg', '15 500 ₽', 20),
    createCourse('f4', 'Лунный Календарь: Ритуалы Полнолуний и Новолуний', 4, '/images/course-feminine-1.jpg', '9 200 ₽', 12),
    createCourse('f5', 'Геката: Магия Перекрёстков и Теневая Работа', 0, '/images/course-feminine-2.jpg', '16 800 ₽', 22),
    createCourse('f6', 'Афродита: Магия Любви и Притяжения', 2, '/images/course-feminine-3.jpg', '12 500 ₽', 14),
    createCourse('f7', 'Артемида: Дикая Женственность и Свобода', 4, '/images/course-feminine-1.jpg', '11 800 ₽', 14),
    createCourse('f8', 'Исцеление Женской Линии Рода: Практики Прощения', 0, '/images/course-feminine-2.jpg', '14 500 ₽', 18),
    createCourse('f9', 'Священная Менструация: Циклы и Сила', 2, '/images/course-feminine-3.jpg', '10 200 ₽', 12),
    createCourse('f10', 'Ведьмин Котёл: Травяная Магия и Зельеварение', 4, '/images/course-feminine-1.jpg', '13 600 ₽', 16),
    createCourse('f11', 'Танец Шакти: Движение как Духовная Практика', 2, '/images/course-feminine-2.jpg', '8 500 ₽', 10),
    createCourse('f12', 'Красная Палатка: Создание Женского Пространства', 0, '/images/course-feminine-3.jpg', '7 900 ₽', 8),
    createCourse('f13', 'Инанна: Нисхождение и Возрождение Женской Силы', 4, '/images/course-feminine-1.jpg', '17 200 ₽', 22),
    createCourse('f14', 'Магия Зеркала: Практики Самопознания', 2, '/images/course-feminine-2.jpg', '9 800 ₽', 12),
    createCourse('f15', 'Дева, Мать, Старуха: Три Лика Богини', 0, '/images/course-feminine-3.jpg', '18 900 ₽', 26),
  ],
  runes: [
    createCourse('r1', 'Старший Футарк: Полный Курс Рунической Магии', 3, '/images/course-runes-1.jpg', '17 900 ₽', 24),
    createCourse('r2', 'Рунические Ставы: Создание и Активация Формул', 3, '/images/course-runes-2.jpg', '12 500 ₽', 15),
    createCourse('r3', 'Руническое Гадание: Искусство Чтения Знаков', 1, '/images/course-runes-3.jpg', '10 900 ₽', 12),
    createCourse('r4', 'Младший Футарк: Скандинавские Руны Викингов', 3, '/images/course-runes-1.jpg', '15 200 ₽', 20),
    createCourse('r5', 'Руна Феху: Привлечение Изобилия и Богатства', 4, '/images/course-runes-2.jpg', '7 900 ₽', 8),
    createCourse('r6', 'Руна Альгиз: Защитные Рунические Практики', 3, '/images/course-runes-3.jpg', '8 500 ₽', 10),
    createCourse('r7', 'Биндруны: Составные Руны и их Магия', 1, '/images/course-runes-1.jpg', '14 800 ₽', 18),
    createCourse('r8', 'Рунические Амулеты: Создание Талисманов', 5, '/images/course-runes-2.jpg', '11 200 ₽', 14),
    createCourse('r9', 'Рунескрипт: Рунические Заклинания и Висы', 3, '/images/course-runes-3.jpg', '16 500 ₽', 22),
    createCourse('r10', 'Руны и Стихии: Элементальная Руническая Магия', 1, '/images/course-runes-1.jpg', '13 800 ₽', 16),
    createCourse('r11', 'Эрилаз: Мастерство Рунического Мага', 3, '/images/course-runes-2.jpg', '22 000 ₽', 30),
    createCourse('r12', 'Руны на Теле: Рунические Практики Исцеления', 0, '/images/course-runes-3.jpg', '10 200 ₽', 12),
    createCourse('r13', 'Утарк: Альтернативный Порядок Рун', 5, '/images/course-runes-1.jpg', '18 500 ₽', 24),
    createCourse('r14', 'Руны и Асатру: Духовная Практика Севера', 3, '/images/course-runes-2.jpg', '14 200 ₽', 18),
    createCourse('r15', 'Рунический Оракул: Продвинутое Гадание', 1, '/images/course-runes-3.jpg', '12 800 ₽', 16),
  ],
  numerology: [
    createCourse('num1', 'Основы Нумерологии: Числа Судьбы и Жизненного Пути', 4, '/images/course-numerology-1.jpg', '9 500 ₽', 12),
    createCourse('num2', 'Каббалистическая Нумерология: Тайны Чисел', 0, '/images/course-numerology-2.jpg', '14 900 ₽', 18),
    createCourse('num3', 'Нумерология Пространства: Числовая Гармония Дома', 4, '/images/course-numerology-3.jpg', '7 900 ₽', 8),
    createCourse('num4', 'Ведическая Нумерология: Числа и Карма', 0, '/images/course-numerology-1.jpg', '13 200 ₽', 16),
    createCourse('num5', 'Мастер-Числа 11, 22, 33: Высшая Вибрация', 4, '/images/course-numerology-2.jpg', '16 500 ₽', 20),
    createCourse('num6', 'Нумерология Имени: Сила Букв и Звуков', 2, '/images/course-numerology-3.jpg', '8 800 ₽', 10),
    createCourse('num7', 'Нумерология Отношений: Совместимость Чисел', 4, '/images/course-numerology-1.jpg', '10 500 ₽', 12),
    createCourse('num8', 'Числовые Циклы: Прогнозирование Событий', 0, '/images/course-numerology-2.jpg', '15 800 ₽', 20),
    createCourse('num9', 'Сакральная Геометрия и Числа: Узоры Вселенной', 1, '/images/course-numerology-3.jpg', '18 200 ₽', 24),
    createCourse('num10', 'Нумерология Бизнеса: Числа Успеха', 4, '/images/course-numerology-1.jpg', '12 900 ₽', 14),
    createCourse('num11', 'Пифагорейская Нумерология: Древняя Школа', 5, '/images/course-numerology-2.jpg', '14 200 ₽', 18),
    createCourse('num12', 'Числовые Медитации: Вибрации Исцеления', 2, '/images/course-numerology-3.jpg', '9 200 ₽', 10),
    createCourse('num13', 'Квадрат Пифагора: Глубинный Анализ Личности', 0, '/images/course-numerology-1.jpg', '11 500 ₽', 14),
    createCourse('num14', 'Нумерология Дат: Выбор Идеального Времени', 4, '/images/course-numerology-2.jpg', '7 500 ₽', 8),
    createCourse('num15', 'Числовая Магия: Ритуалы с Числами Силы', 1, '/images/course-numerology-3.jpg', '19 900 ₽', 26),
  ],
  energy: [
    createCourse('e1', 'Работа с Чакрами: Полное Раскрытие Энергоцентров', 0, '/images/course-energy-1.jpg', '11 500 ₽', 14),
    createCourse('e2', 'Целительный Поток: Энергетическое Исцеление Руками', 4, '/images/course-energy-2.jpg', '13 900 ₽', 16),
    createCourse('e3', 'Кундалини: Пробуждение Змеиной Силы', 1, '/images/course-energy-3.jpg', '19 900 ₽', 28),
    createCourse('e4', 'Аура: Видение, Очищение и Укрепление', 0, '/images/course-energy-1.jpg', '10 200 ₽', 12),
    createCourse('e5', 'Рэйки I-II: Каналы Универсальной Энергии', 4, '/images/course-energy-2.jpg', '15 500 ₽', 20),
    createCourse('e6', 'Рэйки III: Мастерский Уровень', 4, '/images/course-energy-3.jpg', '22 000 ₽', 30),
    createCourse('e7', 'Праническое Целительство: Энергия Жизни', 0, '/images/course-energy-1.jpg', '14 800 ₽', 18),
    createCourse('e8', 'Заземление и Центрирование: Фундамент Практики', 2, '/images/course-energy-2.jpg', '6 900 ₽', 8),
    createCourse('e9', 'Энергетическая Защита: Щиты и Барьеры', 1, '/images/course-energy-3.jpg', '12 400 ₽', 14),
    createCourse('e10', 'Тонкие Тела: Анатомия Энергетического Существа', 5, '/images/course-energy-1.jpg', '16 200 ₽', 20),
    createCourse('e11', 'Меридианы и Цигун: Восточная Энергетическая Работа', 0, '/images/course-energy-2.jpg', '13 500 ₽', 16),
    createCourse('e12', 'Кристаллотерапия: Камни и Энергия', 2, '/images/course-energy-3.jpg', '11 800 ₽', 14),
    createCourse('e13', 'Звукотерапия: Поющие Чаши и Вибрации', 4, '/images/course-energy-1.jpg', '9 900 ₽', 12),
    createCourse('e14', 'Энергия Мест: Геомантия и Лей-Линии', 5, '/images/course-energy-2.jpg', '17 500 ₽', 22),
    createCourse('e15', 'Астральная Проекция: Выход из Тела', 1, '/images/course-energy-3.jpg', '21 000 ₽', 28),
  ],
  voodoo: [
    createCourse('v1', 'Основы Вуду: Космология и Духовная Система', 5, '/images/course-voodoo-1.jpg', '14 500 ₽', 18),
    createCourse('v2', 'Лоа: Знакомство с Духами Вуду', 1, '/images/course-voodoo-2.jpg', '16 200 ₽', 22),
    createCourse('v3', 'Вевé: Священные Символы и их Рисование', 3, '/images/course-voodoo-3.jpg', '11 800 ₽', 14),
    createCourse('v4', 'Алтарь Вуду: Создание Священного Пространства', 0, '/images/course-voodoo-1.jpg', '9 500 ₽', 10),
    createCourse('v5', 'Барон Самеди: Работа с Духами Мёртвых', 5, '/images/course-voodoo-2.jpg', '19 900 ₽', 26),
    createCourse('v6', 'Эрзули Фреда: Магия Любви и Красоты', 2, '/images/course-voodoo-3.jpg', '13 200 ₽', 16),
    createCourse('v7', 'Гри-Гри и Моджо: Создание Магических Мешочков', 3, '/images/course-voodoo-1.jpg', '8 900 ₽', 10),
    createCourse('v8', 'Папа Легба: Открытие Дверей и Перекрёстки', 1, '/images/course-voodoo-2.jpg', '15 800 ₽', 20),
    createCourse('v9', 'Ритуалы Нового Орлеана: Традиция Худу', 5, '/images/course-voodoo-3.jpg', '17 500 ₽', 22),
    createCourse('v10', 'Работа со Свечами в Вуду: Огненная Магия', 0, '/images/course-voodoo-1.jpg', '7 900 ₽', 8),
    createCourse('v11', 'Дамбалла: Мудрость Змея и Начало Всего', 1, '/images/course-voodoo-2.jpg', '18 200 ₽', 24),
    createCourse('v12', 'Защитные Практики Вуду: Обереги и Щиты', 3, '/images/course-voodoo-3.jpg', '10 500 ₽', 12),
    createCourse('v13', 'Петро и Рада: Два Лика Силы', 5, '/images/course-voodoo-1.jpg', '21 000 ₽', 28),
    createCourse('v14', 'Магия Трав в Вуду: Зелья и Омовения', 2, '/images/course-voodoo-2.jpg', '12 400 ₽', 14),
    createCourse('v15', 'Вуду и Предки: Почитание Рода и Связь с Духами', 0, '/images/course-voodoo-3.jpg', '14 800 ₽', 18),
  ],
  alchemy: [
    createCourse('a1', 'Основы Алхимии: Великое Делание и его Стадии', 0, '/images/course-alchemy-1.jpg', '15 500 ₽', 20),
    createCourse('a2', 'Нигредо: Чёрная Стадия Трансформации', 1, '/images/course-alchemy-2.jpg', '12 900 ₽', 16),
    createCourse('a3', 'Альбедо: Очищение и Белая Стадия', 0, '/images/course-alchemy-3.jpg', '12 900 ₽', 16),
    createCourse('a4', 'Рубедо: Красная Стадия и Философский Камень', 1, '/images/course-alchemy-1.jpg', '18 500 ₽', 24),
    createCourse('a5', 'Изумрудная Скрижаль: Тайны Гермеса Трисмегиста', 5, '/images/course-alchemy-2.jpg', '16 200 ₽', 22),
    createCourse('a6', 'Спагирия: Растительная Алхимия на Практике', 0, '/images/course-alchemy-3.jpg', '14 800 ₽', 18),
    createCourse('a7', 'Четыре Элемента: Огонь, Вода, Воздух, Земля', 4, '/images/course-alchemy-1.jpg', '9 200 ₽', 12),
    createCourse('a8', 'Символизм Алхимии: Язык Птиц и Тайные Образы', 1, '/images/course-alchemy-2.jpg', '13 500 ₽', 16),
    createCourse('a9', 'Внутренняя Алхимия: Трансмутация Сознания', 2, '/images/course-alchemy-3.jpg', '17 200 ₽', 22),
    createCourse('a10', 'Алхимия Металлов: Семь Планетарных Сил', 5, '/images/course-alchemy-1.jpg', '15 800 ₽', 20),
    createCourse('a11', 'Парацельс и Ятрохимия: Целительная Алхимия', 0, '/images/course-alchemy-2.jpg', '11 500 ₽', 14),
    createCourse('a12', 'Алхимическая Лаборатория: Практикум Делания', 3, '/images/course-alchemy-3.jpg', '22 000 ₽', 30),
    createCourse('a13', 'Фламель и Философский Камень: История и Практика', 1, '/images/course-alchemy-1.jpg', '10 900 ₽', 12),
    createCourse('a14', 'Алхимия и Юнг: Психологическая Трансмутация', 2, '/images/course-alchemy-2.jpg', '14 200 ₽', 18),
    createCourse('a15', 'Эликсир Бессмертия: Высшая Цель Алхимии', 5, '/images/course-alchemy-3.jpg', '24 900 ₽', 32),
  ],
}

const firstCategory = CATEGORIES[0]
export const DEFAULT_CATEGORY_ID = firstCategory?.id ?? 'sephirotic'
