export type StudentLevel = "beginner" | "intermediate" | "advanced" | "master"

export interface CurriculumCategory {
  id: string
  name: string
  color: string
  bgClass: string
  borderClass: string
}

export interface CurriculumTeacher {
  id: string
  name: string
  avatar: string
}

export interface CurriculumCourse {
  id: string
  title: string
  categoryId: string
  teacherId: string
  level: StudentLevel
  dateStart: string
  dateEnd?: string
  location: string
  isOnline: boolean
  lessons?: number
  price?: string
  schedule?: string
  description: string
}

const avatar = (seed: string) =>
  `https://api.dicebear.com/9.x/avataaars/svg?seed=${seed}&backgroundColor=b6e3f4`

export const curriculumCategories: CurriculumCategory[] = [
  {
    id: "seminars",
    name: "Eira Seminars",
    color: "#5eead4",
    bgClass: "bg-[rgba(94,234,212,0.15)]",
    borderClass: "border-[rgba(94,234,212,0.4)]",
  },
  {
    id: "rituals",
    name: "Eira Rituals",
    color: "#c084fc",
    bgClass: "bg-[rgba(192,132,252,0.15)]",
    borderClass: "border-[rgba(192,132,252,0.4)]",
  },
  {
    id: "immersion",
    name: "Eira Immersion",
    color: "#fbbf24",
    bgClass: "bg-[rgba(251,191,36,0.15)]",
    borderClass: "border-[rgba(251,191,36,0.4)]",
  },
  {
    id: "sintonia",
    name: "Eira Sintonia",
    color: "#f472b6",
    bgClass: "bg-[rgba(244,114,182,0.15)]",
    borderClass: "border-[rgba(244,114,182,0.4)]",
  },
]

export const curriculumTeachers: CurriculumTeacher[] = [
  { id: "elena", name: "Елена Златоцвет", avatar: avatar("elena") },
  { id: "miroslav", name: "Мирослав Огненный", avatar: avatar("miroslav") },
  { id: "irina", name: "Ирина Лунная", avatar: avatar("irina") },
  { id: "velimir", name: "Велимир Руновед", avatar: avatar("velimir") },
  { id: "svetlana", name: "Светлана Звёздная", avatar: avatar("svetlana") },
]

export const studentLevels: { id: StudentLevel; label: string }[] = [
  { id: "beginner", label: "Начинающий" },
  { id: "intermediate", label: "Продолжающий" },
  { id: "advanced", label: "Продвинутый" },
  { id: "master", label: "Мастер" },
]

export function getLevelLabel(level: StudentLevel): string {
  return studentLevels.find((l) => l.id === level)?.label ?? level
}

export function getCategoryById(id: string): CurriculumCategory | undefined {
  return curriculumCategories.find((c) => c.id === id)
}

export function getTeacherById(id: string): CurriculumTeacher | undefined {
  return curriculumTeachers.find((t) => t.id === id)
}

export const curriculumCourses: CurriculumCourse[] = [
  // Сентябрь
  {
    id: "c1",
    title: "15 Аркан. Сила настоящего",
    categoryId: "seminars",
    teacherId: "elena",
    level: "intermediate",
    dateStart: "2025-09-05",
    dateEnd: "2025-09-06",
    location: "Москва",
    isOnline: false,
    lessons: 4,
    price: "18 500 ₽",
    description: "Глубокое погружение в энергию 15-го Аркана Таро. Работа с теневыми аспектами и освобождение скрытого потенциала. Практики трансформации страхов в силу.",
  },
  {
    id: "c2",
    title: "Женский Ритуал. Северный Инь",
    categoryId: "rituals",
    teacherId: "irina",
    level: "beginner",
    dateStart: "2025-09-12",
    location: "Санкт-Петербург",
    isOnline: false,
    lessons: 2,
    price: "12 000 ₽",
    description: "Ритуал пробуждения женской силы через северные архетипы. Работа с энергией Инь, лунными циклами и связью с предками по женской линии.",
  },
  {
    id: "c3",
    title: "Мысль Творца. Новый закон",
    categoryId: "rituals",
    teacherId: "miroslav",
    level: "advanced",
    dateStart: "2025-09-20",
    location: "Онлайн",
    isOnline: true,
    lessons: 3,
    price: "9 900 ₽",
    description: "Практика работы с ментальным планом и законами творения реальности. Техники манифестации через выравнивание мысли и намерения.",
  },
  {
    id: "c4",
    title: "Иерархия Воздуха. Ветер Арктики",
    categoryId: "immersion",
    teacherId: "velimir",
    level: "intermediate",
    dateStart: "2025-09-27",
    location: "Онлайн",
    isOnline: true,
    lessons: 6,
    price: "22 000 ₽",
    schedule: "Пт-Вс, 19:00–22:00",
    description: "Погружение в стихию Воздуха через призму северной традиции. Работа с духами ветра, дыхательные практики и техники ясновидения.",
  },
  // Октябрь
  {
    id: "c5",
    title: "Золотой Ключ 6.0. Магия денег. Часть 1",
    categoryId: "seminars",
    teacherId: "svetlana",
    level: "beginner",
    dateStart: "2025-10-03",
    dateEnd: "2025-10-04",
    location: "Москва",
    isOnline: false,
    lessons: 4,
    price: "16 500 ₽",
    description: "Первая часть курса по денежной магии. Диагностика денежных блоков, работа с родовыми программами и создание нового финансового сценария.",
  },
  {
    id: "c6",
    title: "Тао. Алхимия Инь и Ян",
    categoryId: "sintonia",
    teacherId: "elena",
    level: "intermediate",
    dateStart: "2025-10-11",
    location: "Онлайн",
    isOnline: true,
    lessons: 4,
    price: "14 200 ₽",
    description: "Практика баланса мужской и женской энергий через даосские техники. Медитации, дыхание и работа с меридианами.",
  },
  {
    id: "c7",
    title: "Руны Силы. Защитные ставы",
    categoryId: "seminars",
    teacherId: "velimir",
    level: "intermediate",
    dateStart: "2025-10-18",
    location: "Санкт-Петербург",
    isOnline: false,
    lessons: 3,
    price: "13 500 ₽",
    description: "Создание и активация защитных рунических формул. Практика работы с Альгиз, Турисаз и комбинированными ставами.",
  },
  {
    id: "c8",
    title: "Лунный Портал. Практика Полнолуния",
    categoryId: "rituals",
    teacherId: "irina",
    level: "beginner",
    dateStart: "2025-10-25",
    location: "Онлайн",
    isOnline: true,
    lessons: 1,
    price: "5 500 ₽",
    description: "Ритуал полнолуния для очищения и манифестации. Работа с лунной энергией и женскими архетипами.",
  },
  // Ноябрь
  {
    id: "c9",
    title: "Врата Самайна. Связь с предками",
    categoryId: "rituals",
    teacherId: "miroslav",
    level: "advanced",
    dateStart: "2025-11-01",
    location: "Москва",
    isOnline: false,
    lessons: 2,
    price: "11 000 ₽",
    description: "Ритуал почитания предков в период Самайна. Практики связи с родом и получения мудрости от ушедших.",
  },
  {
    id: "c10",
    title: "Нумерология Судьбы. Мастер-числа",
    categoryId: "seminars",
    teacherId: "svetlana",
    level: "intermediate",
    dateStart: "2025-11-08",
    dateEnd: "2025-11-09",
    location: "Онлайн",
    isOnline: true,
    lessons: 4,
    price: "12 900 ₽",
    description: "Углублённая работа с мастер-числами 11, 22, 33. Расчёт и интерпретация, практическое применение в консультировании.",
  },
  {
    id: "c11",
    title: "Огненная Инициация 3.0",
    categoryId: "immersion",
    teacherId: "miroslav",
    level: "advanced",
    dateStart: "2025-11-15",
    dateEnd: "2025-11-16",
    location: "Сочи",
    isOnline: false,
    lessons: 6,
    price: "28 000 ₽",
    description: "Интенсивное погружение в стихию Огня. Трансформационные практики, работа с Кундалини и внутренним огнём.",
  },
  {
    id: "c12",
    title: "Звуковая Алхимия. Поющие чаши",
    categoryId: "sintonia",
    teacherId: "elena",
    level: "beginner",
    dateStart: "2025-11-22",
    location: "Онлайн",
    isOnline: true,
    lessons: 3,
    price: "8 900 ₽",
    description: "Основы звукотерапии и работы с тибетскими поющими чашами. Техники самоисцеления и гармонизации пространства.",
  },
  {
    id: "c13",
    title: "Сефиротическая Медитация. Тиферет",
    categoryId: "seminars",
    teacherId: "elena",
    level: "intermediate",
    dateStart: "2025-11-29",
    location: "Москва",
    isOnline: false,
    lessons: 2,
    price: "9 500 ₽",
    description: "Медитативная практика на сефиру Тиферет — сердце Древа Жизни. Гармонизация и интеграция противоположностей.",
  },
  // Декабрь
  {
    id: "c14",
    title: "Зимнее Солнцестояние. Ритуал Возрождения",
    categoryId: "rituals",
    teacherId: "irina",
    level: "beginner",
    dateStart: "2025-12-21",
    location: "Онлайн",
    isOnline: true,
    lessons: 1,
    price: "6 500 ₽",
    description: "Ритуал в точку зимнего солнцестояния. Отпускание старого года и закладка намерений на новый цикл.",
  },
  {
    id: "c15",
    title: "Золотой Ключ 6.0. Магия денег. Часть 2",
    categoryId: "seminars",
    teacherId: "svetlana",
    level: "intermediate",
    dateStart: "2025-12-06",
    dateEnd: "2025-12-07",
    location: "Москва",
    isOnline: false,
    lessons: 4,
    price: "16 500 ₽",
    description: "Продолжение курса по денежной магии. Практики привлечения изобилия, работа с денежными эгрегорами и создание финансовых талисманов.",
  },
  {
    id: "c16",
    title: "Йоль. Северная Мистерия",
    categoryId: "immersion",
    teacherId: "velimir",
    level: "intermediate",
    dateStart: "2025-12-20",
    dateEnd: "2025-12-22",
    location: "Санкт-Петербург",
    isOnline: false,
    lessons: 8,
    price: "32 000 ₽",
    description: "Трёхдневное погружение в северную традицию празднования Йоля. Ритуалы, руническая работа и связь с духами зимы.",
  },
  {
    id: "c17",
    title: "Кристаллы Силы. Введение",
    categoryId: "sintonia",
    teacherId: "elena",
    level: "beginner",
    dateStart: "2025-12-13",
    location: "Онлайн",
    isOnline: true,
    lessons: 2,
    price: "7 500 ₽",
    description: "Основы работы с кристаллами и минералами. Выбор, очищение, программирование и использование в практике.",
  },
  // Январь
  {
    id: "c18",
    title: "Новогодний Ритуал. Врата Януса",
    categoryId: "rituals",
    teacherId: "miroslav",
    level: "beginner",
    dateStart: "2026-01-04",
    location: "Онлайн",
    isOnline: true,
    lessons: 1,
    price: "5 000 ₽",
    description: "Ритуал перехода через врата нового года. Работа с архетипом Януса, закрытие старых циклов и открытие новых.",
  },
  {
    id: "c19",
    title: "Каббала для начинающих. Основы",
    categoryId: "seminars",
    teacherId: "elena",
    level: "beginner",
    dateStart: "2026-01-11",
    dateEnd: "2026-01-12",
    location: "Москва",
    isOnline: false,
    lessons: 4,
    price: "14 500 ₽",
    description: "Введение в каббалистическую традицию. Структура Древа Жизни, десять сефирот и 22 пути. Базовые медитации.",
  },
  {
    id: "c20",
    title: "Водная Инициация 2.0",
    categoryId: "immersion",
    teacherId: "irina",
    level: "intermediate",
    dateStart: "2026-01-18",
    dateEnd: "2026-01-19",
    location: "Сочи",
    isOnline: false,
    lessons: 6,
    price: "26 000 ₽",
    description: "Погружение в стихию Воды. Эмоциональное исцеление, работа с подсознанием и лунными энергиями.",
  },
  {
    id: "c21",
    title: "Голос Силы. Гальдр и мантры",
    categoryId: "sintonia",
    teacherId: "velimir",
    level: "intermediate",
    dateStart: "2026-01-25",
    location: "Онлайн",
    isOnline: true,
    lessons: 3,
    price: "11 500 ₽",
    description: "Практика звуковой магии: северный гальдр и восточные мантры. Техники активации голоса как инструмента силы.",
  },
  // Февраль
  {
    id: "c22",
    title: "15 Аркан. Сила настоящего",
    categoryId: "seminars",
    teacherId: "elena",
    level: "intermediate",
    dateStart: "2026-02-21",
    dateEnd: "2026-02-22",
    location: "Москва",
    isOnline: false,
    lessons: 4,
    price: "18 500 ₽",
    description: "Глубокое погружение в энергию 15-го Аркана Таро. Работа с теневыми аспектами и освобождение скрытого потенциала.",
  },
  {
    id: "c23",
    title: "Имболк. Ритуал Пробуждения",
    categoryId: "rituals",
    teacherId: "irina",
    level: "beginner",
    dateStart: "2026-02-01",
    location: "Онлайн",
    isOnline: true,
    lessons: 1,
    price: "5 500 ₽",
    description: "Ритуал праздника Имболк — пробуждение света после зимней тьмы. Работа с богиней Бригид и очищающим огнём.",
  },
  {
    id: "c24",
    title: "Руны Любви. Притяжение и Гармония",
    categoryId: "seminars",
    teacherId: "velimir",
    level: "beginner",
    dateStart: "2026-02-14",
    location: "Санкт-Петербург",
    isOnline: false,
    lessons: 2,
    price: "10 500 ₽",
    description: "Рунические практики для гармонизации отношений. Ставы на любовь, привлечение партнёра и укрепление связи.",
  },
  {
    id: "c25",
    title: "Дыхание Жизни. Пранаяма",
    categoryId: "sintonia",
    teacherId: "elena",
    level: "beginner",
    dateStart: "2026-02-08",
    location: "Онлайн",
    isOnline: true,
    lessons: 4,
    price: "9 200 ₽",
    description: "Основы йогического дыхания. Техники пранаямы для энергии, спокойствия и духовного развития.",
  },
  // Март
  {
    id: "c26",
    title: "Женский Ритуал. Северный Инь",
    categoryId: "rituals",
    teacherId: "irina",
    level: "beginner",
    dateStart: "2026-03-14",
    dateEnd: "2026-03-15",
    location: "Санкт-Петербург",
    isOnline: false,
    lessons: 2,
    price: "12 000 ₽",
    description: "Ритуал пробуждения женской силы через северные архетипы. Работа с энергией Инь и лунными циклами.",
  },
  {
    id: "c27",
    title: "Мысль Творца. Новый закон",
    categoryId: "rituals",
    teacherId: "miroslav",
    level: "advanced",
    dateStart: "2026-03-25",
    location: "Онлайн",
    isOnline: true,
    lessons: 3,
    price: "9 900 ₽",
    description: "Практика работы с ментальным планом и законами творения реальности.",
  },
  {
    id: "c28",
    title: "Остара. Весеннее Равноденствие",
    categoryId: "rituals",
    teacherId: "irina",
    level: "beginner",
    dateStart: "2026-03-20",
    location: "Онлайн",
    isOnline: true,
    lessons: 1,
    price: "5 500 ₽",
    description: "Ритуал весеннего равноденствия. Баланс света и тьмы, посев намерений на новый цикл роста.",
  },
  {
    id: "c29",
    title: "Алхимия Отношений",
    categoryId: "seminars",
    teacherId: "svetlana",
    level: "intermediate",
    dateStart: "2026-03-07",
    dateEnd: "2026-03-08",
    location: "Москва",
    isOnline: false,
    lessons: 4,
    price: "15 500 ₽",
    description: "Трансформация отношений через алхимические принципы. Работа с проекциями, тенью и созданием священного союза.",
  },
  // Апрель
  {
    id: "c30",
    title: "Иерархия Воздуха. Ветер Арктики",
    categoryId: "immersion",
    teacherId: "velimir",
    level: "intermediate",
    dateStart: "2026-04-11",
    location: "Онлайн",
    isOnline: true,
    lessons: 6,
    price: "22 000 ₽",
    schedule: "Сб-Вс, 10:00–17:00",
    description: "Погружение в стихию Воздуха через призму северной традиции.",
  },
  {
    id: "c31",
    title: "Золотой Ключ 6.0. Магия денег. Часть 2",
    categoryId: "seminars",
    teacherId: "svetlana",
    level: "intermediate",
    dateStart: "2026-04-18",
    location: "Онлайн",
    isOnline: true,
    lessons: 4,
    price: "14 500 ₽",
    description: "Продолжение курса по денежной магии. Практики привлечения изобилия.",
  },
  {
    id: "c32",
    title: "Тао. Алхимия Инь и Ян",
    categoryId: "sintonia",
    teacherId: "elena",
    level: "intermediate",
    dateStart: "2026-04-21",
    location: "Онлайн",
    isOnline: true,
    lessons: 4,
    price: "14 200 ₽",
    description: "Практика баланса мужской и женской энергий через даосские техники.",
  },
  {
    id: "c33",
    title: "Белтейн. Огненный Ритуал",
    categoryId: "rituals",
    teacherId: "miroslav",
    level: "beginner",
    dateStart: "2026-04-30",
    location: "Москва",
    isOnline: false,
    lessons: 1,
    price: "8 000 ₽",
    description: "Ритуал праздника Белтейн — празднование жизни, плодородия и священного огня.",
  },
  // Май
  {
    id: "c34",
    title: "Сефиротическая Медитация. Йесод",
    categoryId: "seminars",
    teacherId: "elena",
    level: "intermediate",
    dateStart: "2026-05-09",
    location: "Москва",
    isOnline: false,
    lessons: 2,
    price: "9 500 ₽",
    description: "Медитативная практика на сефиру Йесод — основание и астральный план.",
  },
  {
    id: "c35",
    title: "Руны Исцеления",
    categoryId: "seminars",
    teacherId: "velimir",
    level: "advanced",
    dateStart: "2026-05-16",
    dateEnd: "2026-05-17",
    location: "Санкт-Петербург",
    isOnline: false,
    lessons: 4,
    price: "16 000 ₽",
    description: "Рунические практики для исцеления тела и души. Диагностика и создание целительных ставов.",
  },
  {
    id: "c36",
    title: "Земная Инициация 1.0",
    categoryId: "immersion",
    teacherId: "miroslav",
    level: "beginner",
    dateStart: "2026-05-23",
    dateEnd: "2026-05-24",
    location: "Сочи",
    isOnline: false,
    lessons: 6,
    price: "24 000 ₽",
    description: "Погружение в стихию Земли. Заземление, работа с телом и связь с природными духами.",
  },
  {
    id: "c37",
    title: "Кристаллы Силы. Продвинутый уровень",
    categoryId: "sintonia",
    teacherId: "elena",
    level: "advanced",
    dateStart: "2026-05-30",
    location: "Онлайн",
    isOnline: true,
    lessons: 4,
    price: "13 500 ₽",
    description: "Продвинутые техники работы с кристаллами. Создание кристаллических решёток и целительство.",
  },
  // Июнь
  {
    id: "c38",
    title: "Летнее Солнцестояние. Ритуал Огня",
    categoryId: "rituals",
    teacherId: "irina",
    level: "beginner",
    dateStart: "2026-06-21",
    location: "Онлайн",
    isOnline: true,
    lessons: 1,
    price: "6 500 ₽",
    description: "Ритуал в точку летнего солнцестояния. Празднование света и максимальной солнечной силы.",
  },
  {
    id: "c39",
    title: "Нумерология Бизнеса",
    categoryId: "seminars",
    teacherId: "svetlana",
    level: "intermediate",
    dateStart: "2026-06-06",
    dateEnd: "2026-06-07",
    location: "Москва",
    isOnline: false,
    lessons: 4,
    price: "18 000 ₽",
    description: "Применение нумерологии в бизнесе. Выбор дат, названий, партнёров и стратегий на основе чисел.",
  },
  {
    id: "c40",
    title: "Мастер Рун. Интенсив",
    categoryId: "immersion",
    teacherId: "velimir",
    level: "master",
    dateStart: "2026-06-13",
    dateEnd: "2026-06-15",
    location: "Санкт-Петербург",
    isOnline: false,
    lessons: 10,
    price: "45 000 ₽",
    description: "Мастерский интенсив по руническому искусству. Для практиков с опытом от 3 лет.",
  },
  {
    id: "c41",
    title: "Звуковая Алхимия. Голос и Чакры",
    categoryId: "sintonia",
    teacherId: "elena",
    level: "intermediate",
    dateStart: "2026-06-27",
    location: "Онлайн",
    isOnline: true,
    lessons: 4,
    price: "12 500 ₽",
    description: "Работа с голосом для активации и гармонизации чакр. Тонинг, обертоны и мантры.",
  },
  // Июль
  {
    id: "c42",
    title: "Каббала. Путь Мага",
    categoryId: "seminars",
    teacherId: "elena",
    level: "advanced",
    dateStart: "2026-07-04",
    dateEnd: "2026-07-05",
    location: "Москва",
    isOnline: false,
    lessons: 4,
    price: "19 500 ₽",
    description: "Продвинутая работа с путями на Древе Жизни. Путь Бет и архетип Мага.",
  },
  {
    id: "c43",
    title: "Лугнасад. Ритуал Урожая",
    categoryId: "rituals",
    teacherId: "miroslav",
    level: "beginner",
    dateStart: "2026-07-31",
    location: "Онлайн",
    isOnline: true,
    lessons: 1,
    price: "5 500 ₽",
    description: "Ритуал праздника первого урожая. Благодарность за плоды и подготовка к осени.",
  },
  {
    id: "c44",
    title: "Огненная Инициация 4.0",
    categoryId: "immersion",
    teacherId: "miroslav",
    level: "master",
    dateStart: "2026-07-18",
    dateEnd: "2026-07-20",
    location: "Сочи",
    isOnline: false,
    lessons: 10,
    price: "55 000 ₽",
    description: "Мастерское погружение в стихию Огня. Только для выпускников предыдущих уровней.",
  },
  {
    id: "c45",
    title: "Медитация Единства",
    categoryId: "sintonia",
    teacherId: "irina",
    level: "beginner",
    dateStart: "2026-07-11",
    location: "Онлайн",
    isOnline: true,
    lessons: 4,
    price: "8 500 ₽",
    description: "Практики медитации для переживания единства с собой, другими и миром.",
  },
  // Август
  {
    id: "c46",
    title: "Руны и Таро. Синтез систем",
    categoryId: "seminars",
    teacherId: "velimir",
    level: "advanced",
    dateStart: "2026-08-08",
    dateEnd: "2026-08-09",
    location: "Санкт-Петербург",
    isOnline: false,
    lessons: 4,
    price: "17 500 ₽",
    description: "Интеграция рунической и таро-систем. Соответствия, комбинированные расклады и практики.",
  },
  {
    id: "c47",
    title: "Женский Круг. Сестринство",
    categoryId: "rituals",
    teacherId: "irina",
    level: "beginner",
    dateStart: "2026-08-15",
    location: "Москва",
    isOnline: false,
    lessons: 1,
    price: "7 000 ₽",
    description: "Ритуал женского круга. Практики сестринства, поддержки и совместного творения.",
  },
  {
    id: "c48",
    title: "Водная Инициация 3.0",
    categoryId: "immersion",
    teacherId: "irina",
    level: "advanced",
    dateStart: "2026-08-22",
    dateEnd: "2026-08-24",
    location: "Сочи",
    isOnline: false,
    lessons: 8,
    price: "38 000 ₽",
    description: "Продвинутое погружение в стихию Воды. Глубинное исцеление и работа с коллективным бессознательным.",
  },
  {
    id: "c49",
    title: "Дыхание Жизни. Холотропное дыхание",
    categoryId: "sintonia",
    teacherId: "miroslav",
    level: "intermediate",
    dateStart: "2026-08-29",
    location: "Москва",
    isOnline: false,
    lessons: 2,
    price: "12 000 ₽",
    description: "Практика холотропного дыхания для расширения сознания и интеграции опыта.",
  },
]

export const months = [
  { key: "2025-09", label: "Сентябрь 2025" },
  { key: "2025-10", label: "Октябрь 2025" },
  { key: "2025-11", label: "Ноябрь 2025" },
  { key: "2025-12", label: "Декабрь 2025" },
  { key: "2026-01", label: "Январь 2026" },
  { key: "2026-02", label: "Февраль 2026" },
  { key: "2026-03", label: "Март 2026" },
  { key: "2026-04", label: "Апрель 2026" },
  { key: "2026-05", label: "Май 2026" },
  { key: "2026-06", label: "Июнь 2026" },
  { key: "2026-07", label: "Июль 2026" },
  { key: "2026-08", label: "Август 2026" },
]

export function getCoursesByMonth(monthKey: string): CurriculumCourse[] {
  return curriculumCourses
    .filter((c) => c.dateStart.startsWith(monthKey))
    .sort((a, b) => a.dateStart.localeCompare(b.dateStart))
}

export function getCourseById(id: string): CurriculumCourse | undefined {
  return curriculumCourses.find((c) => c.id === id)
}

export function formatDateRange(dateStart: string, dateEnd?: string): string {
  const start = new Date(dateStart)
  const dayStart = start.getDate().toString().padStart(2, "0")
  const monthStart = (start.getMonth() + 1).toString().padStart(2, "0")

  if (!dateEnd || dateEnd === dateStart) {
    return `${dayStart}.${monthStart}`
  }

  const end = new Date(dateEnd)
  const dayEnd = end.getDate().toString().padStart(2, "0")
  const monthEnd = (end.getMonth() + 1).toString().padStart(2, "0")

  if (monthStart === monthEnd) {
    return `${dayStart}–${dayEnd}.${monthStart}`
  }
  return `${dayStart}.${monthStart}–${dayEnd}.${monthEnd}`
}
