import { categories } from "./courses-data"

export type MaterialType = "article" | "video" | "other"

export interface LibraryAuthor {
  id: string
  name: string
  avatar: string
}

export interface LibraryItem {
  id: string
  title: string
  type: MaterialType
  authorId: string
  authorName: string
  authorAvatar: string
  categoryId: string
  image: string
  date: string
  description: string
}

export const libraryCategories = [
  { id: "all", label: "Статьи от ORA" },
  ...categories.map((c) => ({ id: c.id, label: c.label })),
]

export const libraryAuthors: LibraryAuthor[] = [
  { id: "elena", name: "Елена Златоцвет", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=elena&backgroundColor=b6e3f4" },
  { id: "miroslav", name: "Мирослав Огненный", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=miroslav&backgroundColor=c0aede" },
  { id: "irina", name: "Ирина Лунная", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=irina&backgroundColor=d1d4f9" },
  { id: "velimir", name: "Велимир Руновед", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=velimir&backgroundColor=ffd5dc" },
]

const typeLabels: Record<MaterialType, string> = {
  article: "Статья",
  video: "Видео",
  other: "Иное",
}

export function getTypeLabel(type: MaterialType): string {
  return typeLabels[type]
}

const img = (name: string) => `/images/${name}`

export const libraryItems: LibraryItem[] = [
  {
    id: "lib1",
    title: "Сефиротическая медитация: практика восхождения по Древу",
    type: "article",
    authorId: "elena",
    authorName: libraryAuthors[0].name,
    authorAvatar: libraryAuthors[0].avatar,
    categoryId: "sephirotic",
    image: img("course-sephirotic-1.jpg"),
    date: "15 янв 2025",
    description: "Пошаговая инструкция по медитации на сефирот и настройке на каббалистические энергии.",
  },
  {
    id: "lib2",
    title: "Руны для начинающих: Старший Футарк за один вечер",
    type: "video",
    authorId: "velimir",
    authorName: libraryAuthors[3].name,
    authorAvatar: libraryAuthors[3].avatar,
    categoryId: "runes",
    image: img("course-runes-1.jpg"),
    date: "8 фев 2025",
    description: "Видеоурок с разбором 24 рун Старшего Футарка и базовыми практиками.",
  },
  {
    id: "lib3",
    title: "Лунные ритуалы: от новолуния до полнолуния",
    type: "article",
    authorId: "irina",
    authorName: libraryAuthors[2].name,
    authorAvatar: libraryAuthors[2].avatar,
    categoryId: "feminine",
    image: img("course-feminine-1.jpg"),
    date: "22 янв 2025",
    description: "Календарь лунных фаз и простые ритуалы для каждой фазы цикла.",
  },
  {
    id: "lib4",
    title: "Чакры и аура: диагностика и очищение",
    type: "video",
    authorId: "elena",
    authorName: libraryAuthors[0].name,
    authorAvatar: libraryAuthors[0].avatar,
    categoryId: "energy",
    image: img("course-energy-1.jpg"),
    date: "3 фев 2025",
    description: "Практический вебинар по работе с энергоцентрами и полем ауры.",
  },
  {
    id: "lib5",
    title: "Краткий глоссарий каббалистических терминов",
    type: "other",
    authorId: "miroslav",
    authorName: libraryAuthors[1].name,
    authorAvatar: libraryAuthors[1].avatar,
    categoryId: "sephirotic",
    image: img("course-sephirotic-2.jpg"),
    date: "10 янв 2025",
    description: "Справочник основных понятий: сефирот, пути, парцуф и др.",
  },
  {
    id: "lib6",
    title: "Сейд и северное пророчество: введение",
    type: "article",
    authorId: "irina",
    authorName: libraryAuthors[2].name,
    authorAvatar: libraryAuthors[2].avatar,
    categoryId: "nordic",
    image: img("course-nordic-1.jpg"),
    date: "18 янв 2025",
    description: "История сейда и базовые техники входа в изменённое состояние.",
  },
  {
    id: "lib7",
    title: "Нумерология дня рождения: число жизненного пути",
    type: "video",
    authorId: "elena",
    authorName: libraryAuthors[0].name,
    authorAvatar: libraryAuthors[0].avatar,
    categoryId: "numerology",
    image: img("course-numerology-1.jpg"),
    date: "25 янв 2025",
    description: "Как вычислить число жизненного пути и что оно означает.",
  },
  {
    id: "lib8",
    title: "Лоа в вуду: Барон Самеди и Эрзули",
    type: "article",
    authorId: "miroslav",
    authorName: libraryAuthors[1].name,
    authorAvatar: libraryAuthors[1].avatar,
    categoryId: "voodoo",
    image: img("course-voodoo-1.jpg"),
    date: "5 фев 2025",
    description: "Знакомство с двумя ключевыми духами традиции вуду и способами почитания.",
  },
  {
    id: "lib9",
    title: "Алхимия духа: нигредо и тень",
    type: "article",
    authorId: "miroslav",
    authorName: libraryAuthors[1].name,
    authorAvatar: libraryAuthors[1].avatar,
    categoryId: "alchemy",
    image: img("course-alchemy-1.jpg"),
    date: "12 янв 2025",
    description: "Первый этап Великого Делания в контексте внутренней трансформации.",
  },
  {
    id: "lib10",
    title: "Рунический став на защиту дома",
    type: "video",
    authorId: "velimir",
    authorName: libraryAuthors[3].name,
    authorAvatar: libraryAuthors[3].avatar,
    categoryId: "runes",
    image: img("course-runes-2.jpg"),
    date: "20 янв 2025",
    description: "Мастер-класс по созданию и активации защитного рунического става.",
  },
  {
    id: "lib11",
    title: "Подкаст: Женская магия и циклы",
    type: "other",
    authorId: "irina",
    authorName: libraryAuthors[2].name,
    authorAvatar: libraryAuthors[2].avatar,
    categoryId: "feminine",
    image: img("course-feminine-2.jpg"),
    date: "28 янв 2025",
    description: "Беседа о синхронизации практик с лунными и личными циклами.",
  },
  {
    id: "lib12",
    title: "Девять миров скандинавской космологии",
    type: "article",
    authorId: "velimir",
    authorName: libraryAuthors[3].name,
    authorAvatar: libraryAuthors[3].avatar,
    categoryId: "nordic",
    image: img("course-nordic-2.jpg"),
    date: "1 фев 2025",
    description: "Обзор мифологической географии и связи миров с практикой.",
  },
  {
    id: "lib13",
    title: "Квадрат Пифагора: расчёт и трактовка",
    type: "video",
    authorId: "elena",
    authorName: libraryAuthors[0].name,
    authorAvatar: libraryAuthors[0].avatar,
    categoryId: "numerology",
    image: img("course-numerology-2.jpg"),
    date: "14 янв 2025",
    description: "Построение психоматрицы по дате рождения и чтение основных блоков.",
  },
  {
    id: "lib14",
    title: "Гри-гри: материалы и первый мешочек",
    type: "article",
    authorId: "miroslav",
    authorName: libraryAuthors[1].name,
    authorAvatar: libraryAuthors[1].avatar,
    categoryId: "voodoo",
    image: img("course-voodoo-2.jpg"),
    date: "7 фев 2025",
    description: "Что понадобится для создания гри-гри и пошаговый ритуал.",
  },
  {
    id: "lib15",
    title: "Заземление за 5 минут: техника для ежедневной практики",
    type: "other",
    authorId: "elena",
    authorName: libraryAuthors[0].name,
    authorAvatar: libraryAuthors[0].avatar,
    categoryId: "energy",
    image: img("course-energy-2.jpg"),
    date: "30 янв 2025",
    description: "Краткая аудиомедитация и визуализация для быстрого заземления.",
  },
  {
    id: "lib16",
    title: "Изумрудная скрижаль: текст и комментарий",
    type: "article",
    authorId: "miroslav",
    authorName: libraryAuthors[1].name,
    authorAvatar: libraryAuthors[1].avatar,
    categoryId: "alchemy",
    image: img("course-alchemy-3.jpg"),
    date: "11 фев 2025",
    description: "Полный перевод и разбор ключевых тезисов герметического текста.",
  },
  {
    id: "lib17",
    title: "Малкут и практика заземления в каббале",
    type: "video",
    authorId: "elena",
    authorName: libraryAuthors[0].name,
    authorAvatar: libraryAuthors[0].avatar,
    categoryId: "sephirotic",
    image: img("course-sephirotic-3.jpg"),
    date: "9 фев 2025",
    description: "Связь нижней сефиры с землёй и техниками заземления в практике.",
  },
  {
    id: "lib18",
    title: "Гальдр: звуковые формулы и их применение",
    type: "other",
    authorId: "velimir",
    authorName: libraryAuthors[3].name,
    authorAvatar: libraryAuthors[3].avatar,
    categoryId: "nordic",
    image: img("course-nordic-3.jpg"),
    date: "16 янв 2025",
    description: "Краткий обзор северной магии голоса и примеры формул.",
  },
  {
    id: "lib19",
    title: "Архетипы богини в ритуале",
    type: "article",
    authorId: "irina",
    authorName: libraryAuthors[2].name,
    authorAvatar: libraryAuthors[2].avatar,
    categoryId: "feminine",
    image: img("course-feminine-3.jpg"),
    date: "24 янв 2025",
    description: "Как работать с архетипами Девы, Матери и Старухи в практике.",
  },
  {
    id: "lib20",
    title: "Руна Альгиз: защита и мост между мирами",
    type: "article",
    authorId: "velimir",
    authorName: libraryAuthors[3].name,
    authorAvatar: libraryAuthors[3].avatar,
    categoryId: "runes",
    image: img("course-runes-3.jpg"),
    date: "2 фев 2025",
    description: "Глубокий разбор руны защиты и её использования в ставах.",
  },
  {
    id: "lib21",
    title: "Число души и числа имени в нумерологии",
    type: "video",
    authorId: "elena",
    authorName: libraryAuthors[0].name,
    authorAvatar: libraryAuthors[0].avatar,
    categoryId: "numerology",
    image: img("course-numerology-3.jpg"),
    date: "19 янв 2025",
    description: "Расчёт и интерпретация чисел души и имени по ведической системе.",
  },
  {
    id: "lib22",
    title: "Рэйки: первый уровень — настройка канала",
    type: "article",
    authorId: "elena",
    authorName: libraryAuthors[0].name,
    authorAvatar: libraryAuthors[0].avatar,
    categoryId: "energy",
    image: img("course-energy-3.jpg"),
    date: "6 фев 2025",
    description: "Введение в систему Рэйки и инициация первого уровня.",
  },
  {
    id: "lib23",
    title: "Папа Легба: открытие врат в вуду",
    type: "video",
    authorId: "miroslav",
    authorName: libraryAuthors[1].name,
    authorAvatar: libraryAuthors[1].avatar,
    categoryId: "voodoo",
    image: img("course-voodoo-3.jpg"),
    date: "13 янв 2025",
    description: "Роль Легба в ритуале и простые способы почитания.",
  },
  {
    id: "lib24",
    title: "Три стадии алхимии: от нигредо к рубедо",
    type: "article",
    authorId: "miroslav",
    authorName: libraryAuthors[1].name,
    authorAvatar: libraryAuthors[1].avatar,
    categoryId: "alchemy",
    image: img("course-alchemy-2.jpg"),
    date: "27 янв 2025",
    description: "Обзор трёх фаз Великого Делания и их соответствия внутренней работе.",
  },
]
